version: '3'

services:
  telegram:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sonolillo
    volumes:
      - /docker/sono-lillo/config.js:/app/config.js
    image: dz/sonolillo
    restart: unless-stopped
